### ISSUE TITLE
Question for including a project / general scope 

### ISSUE THREAD

**Issue by serejandmyself** [miguelmota/awesome-token-curated-registries#1]
Hey!

Awesome info on TCR. I would like to add a project, but I am unsure where it would fit, hence not making a PR. 

The project uses blockchain and a ranking mechanism on a knowledge graph to create a search mechanism with the help of IPFS.

I wonder how to find a fit for it on the list, as it seems to me it might fit in perfectly

**Comment by miguelmota** [comment]
Hey @serejandmyself, feel free to make a PR to review

**Comment by serejandmyself** [comment]
Sorry for taking so long with it. Still unsure into which category this should fit:

https://github.com/miguelmota/awesome-token-curated-registries/pull/2

**Comment by serejandmyself** [comment]
Hey @miguelmota wondering if its still relevant?

**Comment by miguelmota** [comment]
I merged it but linked it to the website instead of the github repo since the live section is suppose to be for live sites. Let me know if you rather link the to the repo to put it in a different section like "Projects"

**Comment by serejandmyself** [comment]
I redid it with #3 
changed the site to cyber.page, which is the live site that uses TCR to rank content (somewhat similar to pagerank in google)

**Comment by miguelmota** [comment]
Sounds good, will merge 👍
